version: "3"
services:
  mysql:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - /data/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD = test
      - MYSQL_DATABASE = test
      - MYSQL_USER = mysql
    restart: always
  nginx:
    container_name: nginx
    build: ./requirements/nginx
