version: "3"
services:
  #wordpress:
   # container_name: wordpress
    #volumes:
     # - /home/tcordonn/data:/var/lib/mysql
  mysql:
    container_name: mariadb
    build: ./requirements/mariadb
    #volumes:
      #1- /data/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD = test
      - MYSQL_DATABASE = test
      - MYSQL_USER = mysql
    restart: always
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    volumes:
      - ./requirements/nginx/conf/:/usr/local/etc/nginx/ # needs wordpress data
    ports:
      - 80:80 #443:443
    restart: always
#networks: