version: "3"
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - ${PWD}/requirements/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name      
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass 
    restart:
      always
  nginx:
    
